### ISSUE TITLE
Cannot build with llvm 

### ISSUE THREAD

**Issue by RSSteph** [ghaiklor/llvm-kaleidoscope#1]
I downloaded and build llvm 4.0.0. I tried to build your llvm-kaleidoscope with revised makefile. However, I am getting linking error. I wonder whether you can guide me that how I can proceed. 

Thanks,
[makelog.txt](https://github.com/ghaiklor/llvm-kaleidoscope/files/1160796/makelog.txt)
[Makefile.txt](https://github.com/ghaiklor/llvm-kaleidoscope/files/1160797/Makefile.txt)

**Comment by ghaiklor** [comment]
@RSSteph @HalfVoxel said that PR I've merged should fix your problem.
