### ISSUE TITLE
What IDE do you use？

### ISSUE THREAD

**Issue by woshiccm** [ghaiklor/llvm-kaleidoscope#4]
I use VS, but can't find Head file, what IDE do you use？
![屏幕快照 2020-03-07 下午11.31.01.png](https://upload-images.jianshu.io/upload_images/2086987-9eac37af1be65008.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

**Comment by ghaiklor** [comment]
I don't remember what exactly I used, it was a long time ago. I believe it could be Vim.

**Comment by woshiccm** [comment]
thanks
